version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: qumed
      POSTGRES_USER: qumed
      POSTGRES_DB: qumed
  web:
    build: .
    command: bash -c "python qumed/manage.py makemigrations && python qumed/manage.py migrate && python qumed/manage.py collectstatic --noinput && python qumed/manage.py shell -c 'from django.contrib.auth import get_user_model; User = get_user_model(); superuser = User.objects.get_or_create(username=\"admin\", defaults={\"email\":\"admin@example.com\", \"password\":\"adminpass\", \"is_superuser\":True})' && python qumed/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/qumed
    ports:
      - "8000:8000"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_NAME=qumed"
      - "DATABASE_USER=qumed"
      - "DATABASE_PASSWORD=qumed"
    logging:
      driver: awslogs
      options: 
        awslogs-group: qumed-staging
        awslogs-region: us-east-1
        awslogs-stream-prefix: qumed-staging
    depends_on:
      - db
