# Generated by Django 2.0.2 on 2018-05-30 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_practice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='creator_practice',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_patients', to='referral.Practice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='current_practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_patients', to='referral.Practice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=128, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.IntegerField(unique=True, verbose_name='Medical Record Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='address',
            field=models.CharField(max_length=128, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='practice',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Telephone'),
        ),
    ]
