# Generated by Django 2.0.2 on 2018-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_auto_20180530_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='status',
        ),
        migrations.AddField(
            model_name='referral',
            name='appointment_status',
            field=models.CharField(choices=[('scheduled', 'SCHEDULED'), ('complete', 'COMPLETE'), ('lmts', 'LMTS')], default='lmts', max_length=16),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED')], default='pending', max_length=16),
        ),
    ]
