# Generated by Django 2.0.2 on 2018-07-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_auto_20180615_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('reason_for_referral', models.CharField(max_length=128)),
                ('referred_to_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-date_referred']},
        ),
        migrations.AddField(
            model_name='tempreferral',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.Patient'),
        ),
        migrations.AddField(
            model_name='tempreferral',
            name='referred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.Practice'),
        ),
    ]
