# Generated by Django 2.0.2 on 2018-07-14 23:21

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0005_auto_20180708_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempreferral',
            name='date_referred',
            field=models.DateField(auto_now_add=True, default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='appointment_status',
            field=models.CharField(choices=[('scheduled', 'SCHEDULED'), ('complete', 'COMPLETE'), ('lmts', 'LMTS')], default='lmts', max_length=16, verbose_name='Appointment Status'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='date_referred',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='first_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Attempt'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='notes',
            field=models.TextField(verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='reason_for_referral',
            field=models.CharField(max_length=128, verbose_name='Reason for referral'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED')], default='pending', max_length=16, verbose_name='Referral Status'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='second_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Second Attempt'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='third_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Third Attempt'),
        ),
    ]
