# Generated by Django 2.0.2 on 2019-02-28 18:50

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0010_auto_20180731_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='austin', max_length=32, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=localflavor.us.models.USStateField(default='TX', max_length=2, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(default=70727, max_length=10, verbose_name='ZipCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='city',
            field=models.CharField(default='austin', max_length=32, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='state',
            field=localflavor.us.models.USStateField(default='TX', max_length=2, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(default=70727, max_length=10, verbose_name='ZipCode'),
            preserve_default=False,
        ),
    ]
