# Generated by Django 2.0.2 on 2019-03-04 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0011_auto_20190228_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=datetime.date(2019, 3, 4), verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
