# Generated by Django 2.0.2 on 2018-07-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_auto_20180714_2321'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            ALTER TABLE referral_referral ADD CONSTRAINT cannot_refer_to_self CHECK (
                referral_referral.referred_by_id <> referral_referral.referred_to_id
            );
            ''',
            '''
            ALTER TABLE referral_referral DROP CONSTRAINT cannot_refer_to_self;
            '''
        )
    ]
