# Generated by Django 2.0.2 on 2018-07-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0007_auto_20180719_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_attempt', models.DateTimeField(blank=True, null=True, verbose_name='First Attempt')),
                ('second_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Second Attempt')),
                ('third_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Third Attempt')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Appointment Date')),
                ('appointment_status', models.CharField(choices=[('scheduled', 'SCHEDULED'), ('complete', 'COMPLETE'), ('lmts', 'LMTS')], default='lmts', max_length=16, verbose_name='Appointment Status')),
                ('physician_seen', models.BooleanField(verbose_name='Physician Seen')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.Patient')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.Practice')),
            ],
        ),
        migrations.RemoveField(
            model_name='referral',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='appointment_status',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='first_attempt',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='second_attempt',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='third_attempt',
        ),
    ]
