# Generated by Django 2.0.2 on 2018-07-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0008_auto_20180721_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='physician_seen',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('unset', 'UNSET'), ('lmts', 'LMTS'), ('scheduled', 'SCHEDULED'), ('complete', 'COMPLETE')], default='unset', max_length=16, verbose_name='Appointment Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='referral.Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='practice',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='referral.Practice'),
        ),
    ]
