# Generated by Django 2.0.2 on 2018-07-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0009_auto_20180726_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('lmts', 'LMTS'), ('scheduled', 'SCHEDULED'), ('complete', 'COMPLETE')], max_length=16, verbose_name='Appointment Status'),
        ),
    ]
